using Application.Common;
using Application.DTOs.MasterData;

namespace Application.Interfaces.Repositories;

public interface IMasterDataRepository
{
    Task<IReadOnlyCollection<CountryDto>> GetCountriesAsync(string? search, CancellationToken cancellationToken, bool includeInactive = false);
    Task<IReadOnlyCollection<CountryExportRowDto>> ExportCountriesAsync(CancellationToken cancellationToken);
    Task<CountryDto?> GetCountryAsync(ulong id, CancellationToken cancellationToken);
    Task<CountryDto> CreateCountryAsync(CountryRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<CountryDto?> UpdateCountryAsync(ulong id, CountryRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<CountryDto?> SetCountryActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteCountryAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<StateDto>> GetStatesAsync(ulong? countryId, string? search, CancellationToken cancellationToken, bool includeInactive = false);
    Task<IReadOnlyCollection<StateExportRowDto>> ExportStatesAsync(CancellationToken cancellationToken);
    Task<StateDto?> GetStateAsync(ulong id, CancellationToken cancellationToken);
    Task<StateDto> CreateStateAsync(StateRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<StateDto?> UpdateStateAsync(ulong id, StateRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<StateDto?> SetStateActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteStateAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DistrictDto>> GetDistrictsAsync(ulong? stateId, string? search, CancellationToken cancellationToken, bool includeInactive = false);
    Task<IReadOnlyCollection<DistrictExportRowDto>> ExportDistrictsAsync(CancellationToken cancellationToken);
    Task<DistrictDto?> GetDistrictAsync(ulong id, CancellationToken cancellationToken);
    Task<DistrictDto> CreateDistrictAsync(DistrictRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DistrictDto?> UpdateDistrictAsync(ulong id, DistrictRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DistrictDto?> SetDistrictActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteDistrictAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<CityDto>> GetCitiesAsync(ulong? stateId, ulong? districtId, string? search, CancellationToken cancellationToken, bool includeInactive = false);
    Task<IReadOnlyCollection<CityExportRowDto>> ExportCitiesAsync(CancellationToken cancellationToken);
    Task<CityDto?> GetCityAsync(ulong id, CancellationToken cancellationToken);
    Task<CityDto> CreateCityAsync(CityRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<CityDto?> UpdateCityAsync(ulong id, CityRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<CityDto?> SetCityActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteCityAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<PagedResult<PincodeDto>> GetPincodesAsync(ulong? cityId, string? pincode, int page, int pageSize, CancellationToken cancellationToken, bool includeInactive = false);
    Task<IReadOnlyCollection<PincodeExportRowDto>> ExportPincodesAsync(CancellationToken cancellationToken);
    Task<PincodeDto?> GetPincodeAsync(ulong id, CancellationToken cancellationToken);
    Task<bool> PincodeExistsAsync(string pincode, ulong cityId, ulong? excludeId, CancellationToken cancellationToken);
    Task<PincodeDto> CreatePincodeAsync(PincodeRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<PincodeDto?> UpdatePincodeAsync(ulong id, PincodeRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<PincodeDto?> SetPincodeActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeletePincodeAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<BranchDto>> GetBranchesAsync(string? search, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<BranchDto>> ExportBranchesAsync(CancellationToken cancellationToken);
    Task<BranchDto?> GetBranchAsync(ulong id, CancellationToken cancellationToken);
    Task<bool> BranchNameExistsAsync(string branchName, ulong? excludeId, CancellationToken cancellationToken);
    Task<BranchDto> CreateBranchAsync(BranchRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<BranchDto?> UpdateBranchAsync(ulong id, BranchRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<BranchDto?> SetBranchActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteBranchAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DivisionDto>> GetDivisionsAsync(string? search, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DivisionDto>> ExportDivisionsAsync(CancellationToken cancellationToken);
    Task<DivisionDto?> GetDivisionAsync(ulong id, CancellationToken cancellationToken);
    Task<bool> DivisionNameExistsAsync(string divisionName, ulong? excludeId, CancellationToken cancellationToken);
    Task<DivisionDto> CreateDivisionAsync(DivisionRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DivisionDto?> UpdateDivisionAsync(ulong id, DivisionRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DivisionDto?> SetDivisionActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteDivisionAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DesignationDto>> GetDesignationsAsync(string? search, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DesignationDto>> ExportDesignationsAsync(CancellationToken cancellationToken);
    Task<DesignationDto?> GetDesignationAsync(ulong id, CancellationToken cancellationToken);
    Task<bool> DesignationNameExistsAsync(string designationName, ulong? excludeId, CancellationToken cancellationToken);
    Task<DesignationDto> CreateDesignationAsync(DesignationRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DesignationDto?> UpdateDesignationAsync(ulong id, DesignationRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DesignationDto?> SetDesignationActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteDesignationAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DepartmentDto>> GetDepartmentsAsync(string? search, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<DepartmentDto>> ExportDepartmentsAsync(CancellationToken cancellationToken);
    Task<DepartmentDto?> GetDepartmentAsync(ulong id, CancellationToken cancellationToken);
    Task<bool> DepartmentNameExistsAsync(string name, ulong? excludeId, CancellationToken cancellationToken);
    Task<DepartmentDto> CreateDepartmentAsync(DepartmentRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DepartmentDto?> UpdateDepartmentAsync(ulong id, DepartmentRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<DepartmentDto?> SetDepartmentActiveAsync(ulong id, string? active, ulong? actorUserId, CancellationToken cancellationToken);
    Task<bool> DeleteDepartmentAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<IReadOnlyCollection<LocationDetailsDto>> GetLocationDetailsAsync(string? pincode, ulong? stateId, ulong? cityId, string? city, CancellationToken cancellationToken);
}
