using Shared.Responses;
using Application.DTOs.MasterData;

namespace Application.Interfaces.Services;

public interface IMasterDataService
{
    Task<LaravelApiResponse> GetCountriesAsync(string? search, int? page, int? pageSize, CancellationToken cancellationToken, bool includeInactive = false);
    Task<MasterDataFileDto> ExportCountriesAsync(CancellationToken cancellationToken);
    Task<MasterDataFileDto> GetCountryTemplateAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> UploadCountriesAsync(Stream fileStream, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetCountryAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateCountryAsync(CountryRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateCountryAsync(ulong id, CountryRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetCountryActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteCountryAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetStatesAsync(ulong? countryId, string? search, int? page, int? pageSize, CancellationToken cancellationToken, bool includeInactive = false);
    Task<MasterDataFileDto> ExportStatesAsync(CancellationToken cancellationToken);
    Task<MasterDataFileDto> GetStateTemplateAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> UploadStatesAsync(Stream fileStream, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetStateAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateStateAsync(StateRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateStateAsync(ulong id, StateRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetStateActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteStateAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDistrictsAsync(ulong? stateId, string? search, int? page, int? pageSize, CancellationToken cancellationToken, bool includeInactive = false);
    Task<MasterDataFileDto> ExportDistrictsAsync(CancellationToken cancellationToken);
    Task<MasterDataFileDto> GetDistrictTemplateAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> UploadDistrictsAsync(Stream fileStream, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDistrictAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateDistrictAsync(DistrictRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateDistrictAsync(ulong id, DistrictRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetDistrictActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteDistrictAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetCitiesAsync(ulong? stateId, ulong? districtId, string? search, int? page, int? pageSize, CancellationToken cancellationToken, bool includeInactive = false);
    Task<MasterDataFileDto> ExportCitiesAsync(CancellationToken cancellationToken);
    Task<MasterDataFileDto> GetCityTemplateAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> UploadCitiesAsync(Stream fileStream, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetCityAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateCityAsync(CityRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateCityAsync(ulong id, CityRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetCityActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteCityAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetPincodesAsync(ulong? cityId, string? pincode, int page, int pageSize, CancellationToken cancellationToken, bool includeInactive = false);
    Task<MasterDataFileDto> ExportPincodesAsync(CancellationToken cancellationToken);
    Task<MasterDataFileDto> GetPincodeTemplateAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> UploadPincodesAsync(Stream fileStream, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetPincodeAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreatePincodeAsync(PincodeRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdatePincodeAsync(ulong id, PincodeRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetPincodeActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeletePincodeAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetBranchesAsync(string? search, CancellationToken cancellationToken);
    Task<MasterDataFileDto> ExportBranchesAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetBranchAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateBranchAsync(BranchRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateBranchAsync(ulong id, BranchRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetBranchActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteBranchAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDivisionsAsync(string? search, CancellationToken cancellationToken);
    Task<MasterDataFileDto> ExportDivisionsAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDivisionAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateDivisionAsync(DivisionRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateDivisionAsync(ulong id, DivisionRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetDivisionActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteDivisionAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDesignationsAsync(string? search, CancellationToken cancellationToken);
    Task<MasterDataFileDto> ExportDesignationsAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDesignationAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateDesignationAsync(DesignationRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateDesignationAsync(ulong id, DesignationRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetDesignationActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteDesignationAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDepartmentsAsync(string? search, CancellationToken cancellationToken);
    Task<MasterDataFileDto> ExportDepartmentsAsync(CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetDepartmentAsync(ulong id, CancellationToken cancellationToken);
    Task<LaravelApiResponse> CreateDepartmentAsync(DepartmentRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> UpdateDepartmentAsync(ulong id, DepartmentRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> SetDepartmentActiveAsync(ulong id, ActiveStatusRequestDto request, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> DeleteDepartmentAsync(ulong id, ulong? actorUserId, CancellationToken cancellationToken);
    Task<LaravelApiResponse> GetLocationDetailsAsync(string? pincode, ulong? stateId, ulong? cityId, string? city, CancellationToken cancellationToken);
}
