// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528060200_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasColumnName("branch_code");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("branch_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.Property<string>("WarehouseId")
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchName");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("city_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<ulong?>("DistrictId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("district_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("grade");

                    b.Property<ulong?>("StateId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("state_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CityName");

                    b.HasIndex("DistrictId");

                    b.HasIndex("StateId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("country_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CountryName");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<ulong?>("BeatScheduleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("beatscheduleid");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomFields")
                        .HasColumnType("longtext")
                        .HasColumnName("custom_fields");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("")
                        .HasColumnName("customer_code");

                    b.Property<ulong?>("CustomerType")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("customertype");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("device_type");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("email");

                    b.Property<ulong?>("ExecutiveId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("executive_id");

                    b.Property<ulong?>("FirmType")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("firmtype");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("longitude");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("")
                        .HasColumnName("manager_name");

                    b.Property<string>("ManagerPhone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("manager_phone");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasDefaultValue("")
                        .HasColumnName("notification_id");

                    b.Property<string>("Otp")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("otp");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parent_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasDefaultValue("")
                        .HasColumnName("profile_image");

                    b.Property<ulong?>("RegionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("region_id");

                    b.Property<bool?>("SameAddress")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("same_address");

                    b.Property<string>("SapCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sap_code");

                    b.Property<string>("ShopImage")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("shop_image");

                    b.Property<ulong?>("StatusId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Designation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("designation_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DesignationName");

                    b.ToTable("designations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.District", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("district_name");

                    b.Property<ulong?>("StateId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("state_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DistrictName");

                    b.HasIndex("StateId");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Division", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("division_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DivisionName");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MobileUserLoginDetail", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("App")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("app");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("app_version");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CustomerId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_type");

                    b.Property<DateTime?>("FirstLoginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_login_date");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_date");

                    b.Property<DateTime?>("LoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_at");

                    b.Property<string>("LoginStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("login_status");

                    b.Property<string>("MultiLogin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("multi_login");

                    b.Property<string>("UniqueId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("unique_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("mobile_user_login_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ModelHasPermission", b =>
                {
                    b.Property<ulong>("PermissionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("permission_id");

                    b.Property<ulong>("ModelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_type");

                    b.HasKey("PermissionId", "ModelId", "ModelType");

                    b.ToTable("model_has_permissions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ModelHasRole", b =>
                {
                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.Property<ulong>("ModelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_type");

                    b.HasKey("RoleId", "ModelId", "ModelType");

                    b.ToTable("model_has_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NewInvoice", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovalRemark")
                        .HasColumnType("text")
                        .HasColumnName("approval_remark");

                    b.Property<int>("ApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedHoAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_ho_at");

                    b.Property<ulong?>("ApprovedHoBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("approved_ho_by");

                    b.Property<DateTime?>("ApprovedSalesAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_sales_at");

                    b.Property<ulong?>("ApprovedSalesBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("approved_sales_by");

                    b.Property<DateTime?>("ApprovedSsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_ss_at");

                    b.Property<ulong?>("ApprovedSsBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("approved_ss_by");

                    b.Property<string>("Attachment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("attachment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invoice_number");

                    b.Property<decimal>("Points")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("points");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rejected_at");

                    b.Property<ulong?>("RejectedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("rejected_by");

                    b.Property<ulong>("SecondaryCustomerId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("secondary_customer_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("SecondaryCustomerId");

                    b.ToTable("new_invoices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NewInvoiceApprovalLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int")
                        .HasColumnName("from_status");

                    b.Property<DateTime?>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<ulong?>("NewInvoiceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("new_invoice_id");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("StatusType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status_type");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("int")
                        .HasColumnName("to_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NewInvoiceId");

                    b.ToTable("new_invoice_approval_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OAuthAccessToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<ulong>("ClientId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("oauth_access_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GuardName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("guard_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name", "GuardName")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pincode", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<ulong?>("CityId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("pincode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PinCode");

                    b.ToTable("pincodes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("display_name");

                    b.Property<long>("HsnSac")
                        .HasColumnType("bigint")
                        .HasColumnName("hsn_sac");

                    b.Property<string>("ModelNo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("model_no");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("part_no");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("product_image");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("product_no");

                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("ranking");

                    b.Property<string>("SapCode")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)")
                        .HasColumnName("sap_code");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("specification");

                    b.Property<ulong?>("SubcategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("subcategory_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductCategory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("category_image");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("ranking");

                    b.Property<string>("SapCode")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("sap_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductDetail", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DetailDescription")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("detail_description");

                    b.Property<string>("DetailImage")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("detail_image");

                    b.Property<string>("DetailTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("detail_title");

                    b.Property<decimal?>("Mrp")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("mrp");

                    b.Property<decimal?>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("price");

                    b.Property<ulong?>("ProductId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("SellingPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("selling_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("product_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductFamily", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("ranking");

                    b.Property<string>("SapCode")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("sap_code");

                    b.Property<string>("ServiceCategoryId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("service_category_id");

                    b.Property<string>("SubcategoryImage")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("subcategory_image");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("subcategory_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GuardName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("guard_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name", "GuardName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RoleHasPermission", b =>
                {
                    b.Property<ulong>("PermissionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("permission_id");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.HasKey("PermissionId", "RoleId");

                    b.ToTable("role_has_permissions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.State", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<ulong?>("CountryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GstCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gst_code");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("state_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateName");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("blood_group");

                    b.Property<string>("BranchId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("branch_id");

                    b.Property<string>("BranchShow")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branch_show");

                    b.Property<decimal?>("CasualLeaveBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("casual_leave_balance");

                    b.Property<decimal?>("ClaimableEarnedLeaveBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("claimable_earned_leave_balance");

                    b.Property<decimal?>("CompbOff")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compb_off");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<ulong?>("CustomerId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("customerid");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_joining");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<ulong?>("DepartmentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("department_id");

                    b.Property<ulong?>("DesignationId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("designation_id");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("device_type");

                    b.Property<ulong?>("DivisionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("division_id");

                    b.Property<decimal?>("EarnedLeaveBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("earned_leave_balance");

                    b.Property<DateTime?>("EarnedLeaveClaimActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("earned_leave_claim_activated_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("EmployeeCodes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("employee_codes");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("gender");

                    b.Property<string>("Grade")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("LastLeaveAccrualDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_leave_accrual_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("latitude");

                    b.Property<decimal>("LeaveBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("leave_balance");

                    b.Property<string>("Location")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("")
                        .HasColumnName("location");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("longitude");

                    b.Property<string>("Mobile")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasDefaultValue("")
                        .HasColumnName("notification_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordString")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_string");

                    b.Property<string>("Payroll")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("payroll");

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("personal_number");

                    b.Property<ulong?>("PrimaryBranchId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("primary_branch_id");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasDefaultValue("")
                        .HasColumnName("profile_image");

                    b.Property<ulong?>("RegionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("region_id");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("remember_token");

                    b.Property<ulong?>("ReportingId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("reportingid");

                    b.Property<string>("SalesType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("sales_type");

                    b.Property<string>("ShowAttandanceReport")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("show_attandance_report");

                    b.Property<decimal?>("SickLeaveBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sick_leave_balance");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("user_code");

                    b.Property<ulong?>("WarehouseId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("ReportingId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserCityAssign", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("CityId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<ulong?>("ReportingId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("reportingid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ReportingId");

                    b.HasIndex("UserId");

                    b.ToTable("user_city_assigns", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserDetails", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AadharNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("aadhar_number");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("account_number");

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BiometricCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("biometric_code");

                    b.Property<string>("ChildrenFive")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("children_five");

                    b.Property<DateTime?>("ChildrenFiveDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("children_five_date_of_birth");

                    b.Property<string>("ChildrenFour")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("children_four");

                    b.Property<DateTime?>("ChildrenFourDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("children_four_date_of_birth");

                    b.Property<string>("ChildrenOne")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("children_one");

                    b.Property<DateTime?>("ChildrenOneDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("children_one_date_of_birth");

                    b.Property<string>("ChildrenThree")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("children_three");

                    b.Property<DateTime?>("ChildrenThreeDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("children_three_date_of_birth");

                    b.Property<string>("ChildrenTwo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("children_two");

                    b.Property<DateTime?>("ChildrenTwoDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("children_two_date_of_birth");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CtcAnnual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ctc_annual");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("text")
                        .HasColumnName("current_address");

                    b.Property<string>("CurrentCompanyTenture")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("current_company_tenture");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DateOfConfirmation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_confirmation");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_joining");

                    b.Property<DateTime?>("DateOfLeaving")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_leaving");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmergencyNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("emergency_number");

                    b.Property<string>("EsiNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("esi_number");

                    b.Property<DateTime?>("FatherDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("father_date_of_birth");

                    b.Property<string>("FatherName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("father_name");

                    b.Property<decimal>("GrossSalaryMonthly")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_salary_monthly");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ifsc_code");

                    b.Property<string>("LastPromotion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_promotion");

                    b.Property<string>("LastYearIncrementPercent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_year_increment_percent");

                    b.Property<decimal>("LastYearIncrementValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("last_year_increment_value");

                    b.Property<decimal>("LastYearIncrements")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("last_year_increments");

                    b.Property<string>("MaritalStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("marital_status");

                    b.Property<DateTime?>("MarriageAnniversary")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("marriage_anniversary");

                    b.Property<DateTime?>("MotherDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("mother_date_of_birth");

                    b.Property<string>("MotherName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mother_name");

                    b.Property<string>("NoticePeriod")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notice_period");

                    b.Property<string>("OrderMails")
                        .HasColumnType("text")
                        .HasColumnName("order_mails");

                    b.Property<string>("OrderMailsType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("order_mails_type");

                    b.Property<string>("OtherEducation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("other_education");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pan_number");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("text")
                        .HasColumnName("permanent_address");

                    b.Property<string>("PfNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pf_number");

                    b.Property<string>("PreviousExp")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("previous_exp");

                    b.Property<string>("ProbationPeriod")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("probation_period");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("SpouseDateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("spouse_date_of_birth");

                    b.Property<string>("SpouseName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("spouse_name");

                    b.Property<string>("TotalExp")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("total_exp");

                    b.Property<string>("UnNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("un_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserEducation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("BoardName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("board_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DegreeName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("degree_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<ulong?>("EducationTypeId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("education_type_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("grade");

                    b.Property<string>("Percentage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("percentage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_education", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ModelHasPermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Domain.Entities.ModelHasRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
